name: Build and Benchmark all 

on:
  push:


jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        run: sh build-all.sh

      - name: benchmark
        run: python3 benchmark.py
